# This configuration file is necessary for constants used
#  in the DynamicCraftPlugin

urls:
  test: true
  uat: https://uat.craftsilicon.com
  live: https://app.craftsilicon.com
  tokenUrl: /ElmaAuthDynamicV3/api/auth/apps

request:
  trxSource: APP
  versionNumber: 1
  bankId: 8888
  appName: BRACMOBILE
  country: UGANDATEST

crypt:
  staticEncryptKey: csXDRzpcEPm_jMny
  staticEncryptIv: 84jfkfndl3ybdfkf
  staticLogKeyValue: KBSB&er3bflx9%

appProperties:
  appLabel: BracMobile
  appPrimaryColor: 8A1D5C
  appSecondaryColor: E10086
